import { config } from "./config.js";
import { buildReport } from "./report.js";
import { LeadStore } from "./store.js";
import type { Lead } from "./types.js";
import { escapeHtml } from "./utils.js";

function stageCount(report: ReturnType<typeof buildReport>, stage: keyof typeof report.counts): number {
  return report.counts[stage] ?? 0;
}

function stageLabel(stage: Lead["stage"]): string {
  return stage.replaceAll("_", " ");
}

function stageClass(stage: Lead["stage"]): string {
  if (stage === "qualified") return "qualified";
  if (stage === "demo_ready" || stage === "approved") return "demo";
  return "";
}

function initials(name: string): string {
  return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase() ?? "").join("");
}

function primarySignal(lead: Lead): string {
  return lead.score?.items?.[0]?.label ?? (lead.website ? "Audit complete" : "Website not found");
}

function topSignals(lead: Lead | undefined): string[] {
  if (!lead) return [];
  const labels = (lead.score?.items ?? []).slice(0, 3).map((item) => item.label);
  return labels.length ? labels : [lead.website ? "No major opportunity signal recorded yet" : "No own website identified during discovery"];
}

function websiteLink(lead: Lead, label = "Open ↗"): string {
  return lead.website
    ? `<a class="mini-link" href="${escapeHtml(lead.website)}" target="_blank" rel="noreferrer">${label}</a>`
    : `<span class="muted">Not found</span>`;
}

function actionMarkup(lead: Lead): string {
  if (lead.stage === "demo_ready") {
    return `<button class="secondary-btn" onclick="approve('${escapeHtml(lead.id)}')">Approve outreach</button>`;
  }
  if (lead.stage === "approved") {
    const send = lead.contactEmail
      ? `<button class="secondary-btn" onclick="sendZoho('${escapeHtml(lead.id)}')">Send via Zoho</button>`
      : `<span class="muted">No contact email</span>`;
    return `${send}<button class="outline-btn" onclick="stage('${escapeHtml(lead.id)}','contacted')">Mark contacted manually</button>`;
  }
  return "";
}

function flowIcon(name: string): string {
  const icons: Record<string, string> = {
    Find: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="11" cy="11" r="6"/><path d="m20 20-4-4"/></svg>',
    Audit: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M5 4h14v16H5zM8 8h8M8 12h5"/></svg>',
    Demo: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 5h16v14H4zM4 9h16M8 13h8"/></svg>',
    Approve: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m5 12 4 4L19 6"/></svg>',
    Contact: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 5h16v14H4zM4 7l8 6 8-6"/></svg>',
    Close: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M5 12h14M12 5l7 7-7 7"/></svg>'
  };
  return icons[name] ?? "";
}

const CSS = String.raw`
@import url('https://fonts.googleapis.com/css2?family=Sora:wght@500;600;700&family=Inter:wght@400;500;600;700&display=swap');
:root{--ink:#101828;--muted:#667085;--subtle:#98a2b3;--line:#e4e7ec;--line-strong:#d0d5dd;--bg:#f5f7fb;--surface:#fff;--nav:#0b1220;--nav-2:#111b2e;--brand:#315bff;--brand-soft:#edf1ff;--success:#079455;--warning:#dc6803;--radius:14px;--shadow-sm:0 2px 8px rgba(16,24,40,.06);--sidebar:248px;--topbar:72px;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--ink);min-height:100vh}::selection{background:#cbd5ff;color:#101828}button,input{font:inherit}button{cursor:pointer}a{color:inherit;text-decoration:none}:focus-visible{outline:3px solid rgba(49,91,255,.32);outline-offset:3px;border-radius:8px}
.app{display:grid;grid-template-columns:var(--sidebar) minmax(0,1fr);min-height:100vh}.sidebar{position:sticky;top:0;height:100vh;background:var(--nav);color:#d9e0ec;padding:22px 16px 18px;display:flex;flex-direction:column;border-right:1px solid rgba(255,255,255,.05)}.brand{height:54px;display:flex;align-items:center;gap:12px;padding:0 8px 18px;border-bottom:1px solid rgba(255,255,255,.08)}.brand-mark,.logo-wrap{width:38px;height:38px;border-radius:10px;background:#fff;display:grid;place-items:center;overflow:hidden;box-shadow:0 4px 14px rgba(0,0,0,.18);color:var(--brand);font-family:Sora,sans-serif;font-size:12px;font-weight:800}.logo-wrap img{width:100%;height:100%;object-fit:contain}.brand-copy strong{display:block;font-family:Sora,sans-serif;font-size:15px;color:#fff;letter-spacing:-.01em}.brand-copy span{display:block;font-size:11px;color:#8fa0bb;margin-top:2px}.nav{display:grid;gap:4px;margin-top:18px}.nav-label{font-size:10px;text-transform:uppercase;letter-spacing:.13em;color:#6f819f;font-weight:700;padding:10px 12px 6px}.nav a{min-height:42px;display:flex;align-items:center;gap:11px;padding:0 12px;border-radius:10px;color:#aebbd0;font-size:13px;font-weight:600;transition:background .18s ease,color .18s ease}.nav a:hover{background:rgba(255,255,255,.06);color:#fff}.nav a.active{background:#1a2740;color:#fff;box-shadow:inset 0 0 0 1px rgba(105,133,255,.2)}.nav svg{width:18px;height:18px;stroke-width:1.9}.nav-badge{margin-left:auto;min-width:20px;height:20px;padding:0 6px;border-radius:999px;background:#233454;color:#cbd5e1;font-size:10px;display:grid;place-items:center}.sidebar-footer{margin-top:auto;padding:14px 10px 2px}.system-card{border-top:1px solid rgba(255,255,255,.08);padding-top:15px;display:flex;gap:10px;align-items:center}.status-dot{width:9px;height:9px;border-radius:50%;background:#21c67a;box-shadow:0 0 0 4px rgba(33,198,122,.12)}.system-card strong{display:block;color:#fff;font-size:12px}.system-card span{display:block;color:#7f91ad;font-size:10px;margin-top:2px}
.main{min-width:0}.topbar{height:var(--topbar);background:rgba(255,255,255,.96);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 28px;position:sticky;top:0;z-index:20;backdrop-filter:saturate(120%) blur(10px)}.page-title{display:flex;align-items:center;gap:12px}.page-title h1{font-family:Sora,sans-serif;font-size:18px;line-height:1;margin:0;letter-spacing:-.02em}.top-actions{display:flex;align-items:center;gap:10px}.icon-btn{width:40px;height:40px;border:1px solid var(--line);background:#fff;border-radius:10px;color:#475467;display:grid;place-items:center}.icon-btn svg{width:18px;height:18px}.primary{height:40px;border:0;border-radius:10px;background:var(--brand);color:#fff;padding:0 15px;font-size:12px;font-weight:700;display:flex;align-items:center;gap:8px;box-shadow:0 6px 16px rgba(49,91,255,.22)}.primary:hover{background:#244cf1;transform:translateY(-1px)}.primary svg{width:16px;height:16px}.mobile-menu{display:none}.content{padding:26px 28px 48px;max-width:1540px;margin:0 auto}.intro{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:22px}.intro h2{font-family:Sora,sans-serif;font-size:28px;letter-spacing:-.035em;line-height:1.15;margin:0}.intro p{margin:8px 0 0;color:var(--muted);font-size:13px;max-width:760px;line-height:1.6}.live-status{display:flex;align-items:center;gap:8px;font-size:11px;color:#344054;font-weight:600}.live-status i{width:8px;height:8px;border-radius:50%;background:#17b26a;box-shadow:0 0 0 5px #ecfdf3}
.workflow{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);padding:17px 18px;display:grid;grid-template-columns:repeat(6,1fr);margin-bottom:18px;box-shadow:var(--shadow-sm)}.flow-step{position:relative;display:flex;align-items:center;gap:10px;min-width:0;padding:0 12px}.flow-step:first-child{padding-left:0}.flow-step:last-child{padding-right:0}.flow-step:not(:last-child)::after{content:"";position:absolute;right:-1px;top:17px;width:2px;height:2px;border-radius:50%;background:#b9c0cc;box-shadow:5px 0 0 #b9c0cc,10px 0 0 #b9c0cc}.step-icon{width:34px;height:34px;border-radius:10px;background:#f2f4f7;color:#475467;display:grid;place-items:center;flex:0 0 auto}.flow-step.is-live .step-icon{background:var(--brand-soft);color:var(--brand)}.step-icon svg{width:17px;height:17px}.flow-step strong{font-size:11px;display:block}.flow-step span{font-size:10px;color:var(--muted);display:block;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.metrics{background:#fff;border:1px solid var(--line);border-radius:var(--radius);display:grid;grid-template-columns:repeat(6,1fr);margin-bottom:18px;box-shadow:var(--shadow-sm);overflow:hidden}.metric{padding:17px 18px;min-width:0}.metric:not(:last-child){border-right:1px solid var(--line)}.metric-label{font-size:11px;color:var(--muted);font-weight:600}.metric-value{font-family:Sora,sans-serif;font-size:26px;font-weight:700;letter-spacing:-.035em;margin-top:8px;font-variant-numeric:tabular-nums}.metric-foot{font-size:10px;color:#98a2b3;margin-top:5px}
.grid-top{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(300px,.75fr);gap:18px;margin-bottom:18px}.panel{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow-sm);min-width:0}.panel-head{padding:17px 18px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;gap:14px}.panel-head h3{font-family:Sora,sans-serif;font-size:14px;margin:0;letter-spacing:-.015em}.panel-head p{font-size:10px;color:var(--muted);margin:4px 0 0}.text-link{font-size:11px;color:var(--brand);font-weight:700}.pipeline-body{padding:20px 18px}.pipeline-rail{height:12px;border-radius:999px;overflow:hidden;display:flex;background:#f2f4f7;margin-bottom:19px}.seg{height:100%}.s1{background:#d9e0ff}.s2{background:#aab8ff}.s3{background:#7289ff}.s4{background:#4668ff}.s5{background:#23bca9}.s6{background:#079455}.stage-list{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.stage{padding:10px 0}.stage strong{font-family:Sora,sans-serif;font-size:18px;display:block}.stage span{font-size:10px;color:var(--muted);display:block;margin-top:4px}.stage em{display:block;width:7px;height:7px;border-radius:2px;margin-bottom:8px}.stage:nth-child(1) em{background:#d9e0ff}.stage:nth-child(2) em{background:#aab8ff}.stage:nth-child(3) em{background:#7289ff}.stage:nth-child(4) em{background:#4668ff}.stage:nth-child(5) em{background:#23bca9}.stage:nth-child(6) em{background:#079455}
.opportunity{padding:18px}.opp-top{display:flex;justify-content:space-between;gap:15px;align-items:flex-start}.opp-score{width:58px;height:58px;border-radius:14px;background:#eef2ff;color:#2949d3;display:grid;place-content:center;text-align:center;flex:0 0 auto}.opp-score strong{font-family:Sora,sans-serif;font-size:21px;line-height:1}.opp-score span{font-size:9px;font-weight:700;text-transform:uppercase;letter-spacing:.08em;margin-top:3px}.opportunity h4{font-family:Sora,sans-serif;font-size:16px;margin:0 0 5px}.opportunity .meta{font-size:11px;color:var(--muted)}.signal-list{display:grid;gap:8px;margin:18px 0}.signal{display:flex;align-items:center;gap:9px;font-size:11px;color:#344054}.signal i{width:7px;height:7px;border-radius:2px;background:#f79009}.opp-actions{display:flex;gap:8px}.secondary-btn,.outline-btn{min-height:36px;border-radius:9px;padding:0 12px;font-size:11px;font-weight:700;display:inline-flex;align-items:center;justify-content:center}.secondary-btn{border:0;background:#101828;color:#fff}.outline-btn{background:#fff;border:1px solid var(--line-strong);color:#344054}.action-link{text-decoration:none}
.workspace{margin-bottom:18px;overflow:hidden}.workspace-toolbar{display:flex;align-items:center;gap:10px}.search{height:36px;border:1px solid var(--line);background:#fff;border-radius:9px;display:flex;align-items:center;gap:8px;padding:0 10px;min-width:220px}.search svg{width:15px;height:15px;color:#98a2b3}.search input{border:0;outline:0;width:100%;font-size:11px;background:transparent;color:var(--ink)}.filter-btn{height:36px;border:1px solid var(--line);background:#fff;border-radius:9px;padding:0 11px;font-size:11px;color:#344054;font-weight:600}.lead-table{width:100%;border-collapse:collapse}.lead-table th{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#98a2b3;background:#fafbfd;text-align:left;padding:10px 16px;border-bottom:1px solid var(--line)}.lead-table td{padding:13px 16px;border-bottom:1px solid var(--line);font-size:11px;color:#344054;vertical-align:middle}.lead-table tr:last-child td{border-bottom:0}.lead-name{display:flex;align-items:center;gap:10px}.avatar{width:34px;height:34px;border-radius:9px;background:#eef2ff;color:#315bff;display:grid;place-items:center;font-size:10px;font-weight:800}.lead-name strong{display:block;color:var(--ink);font-size:11px}.lead-name span{display:block;color:#98a2b3;font-size:9px;margin-top:3px}.score-num{font-family:Sora,sans-serif;font-weight:700;color:var(--ink)}.stage-pill{display:inline-flex;align-items:center;height:26px;padding:0 8px;border-radius:999px;font-size:10px;font-weight:700;background:#f2f4f7;color:#344054;text-transform:capitalize}.stage-pill.qualified{background:#edf1ff;color:#2949d3}.stage-pill.demo{background:#e8fbf7;color:#087f72}.mini-link{color:var(--brand);font-weight:700}.table-actions{display:flex;flex-wrap:wrap;gap:6px}.table-actions .secondary-btn,.table-actions .outline-btn{min-height:32px;padding:0 9px}.mobile-leads{display:none}.muted{color:var(--muted);font-size:10px}.empty-state{padding:30px 18px;text-align:center;color:var(--muted)}.empty-state strong{display:block;color:var(--ink);font-size:14px;margin-bottom:6px}
.bottom-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:18px}.ops-list,.health{padding:4px 18px}.agent-row,.health-row{display:flex;align-items:center;gap:11px;padding:13px 0;border-bottom:1px solid var(--line)}.agent-row:last-child,.health-row:last-child{border-bottom:0}.agent-icon{width:34px;height:34px;border-radius:10px;background:#f2f4f7;color:#475467;display:grid;place-items:center}.agent-icon svg{width:17px;height:17px}.agent-copy{min-width:0;flex:1}.agent-copy strong,.health-row strong{display:block;font-size:11px}.agent-copy span,.health-row span:not(.health-status){display:block;color:#98a2b3;font-size:9px;margin-top:3px}.agent-state,.health-status{font-size:9px;font-weight:700;padding:5px 8px;border-radius:999px;background:#ecfdf3;color:#067647;white-space:nowrap}.agent-state.idle,.health-status.warn{background:#fff4ed;color:#b54708}.legal-panel{margin-bottom:70px}.overlay{display:none}.mobile-bottom-nav{display:none}
@media(max-width:1200px){.metrics{grid-template-columns:repeat(3,1fr)}.metric:nth-child(3){border-right:0}.metric:nth-child(-n+3){border-bottom:1px solid var(--line)}.workflow{grid-template-columns:repeat(3,1fr);gap:14px}.flow-step:not(:last-child)::after{display:none}.stage-list{grid-template-columns:repeat(3,1fr)}}
@media(max-width:900px){.app{grid-template-columns:210px minmax(0,1fr)}.grid-top,.bottom-grid{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}.metric{border-bottom:1px solid var(--line)}.metric:nth-child(even){border-right:0}.stage-list{grid-template-columns:repeat(3,1fr)}}
@media(max-width:760px){body{padding-bottom:76px}.app{display:block}.sidebar{position:fixed;left:-280px;top:0;width:260px;height:100vh;z-index:60;transition:left .2s ease}.sidebar.open{left:0}.overlay{position:fixed;inset:0;background:rgba(3,8,16,.45);z-index:50;display:none}.overlay.show{display:block}.topbar{height:62px;padding:0 12px;position:sticky}.mobile-menu{display:grid}.page-title h1{font-size:14px;max-width:190px;line-height:1.15}.top-actions .icon-btn{display:none}.primary{min-height:44px}.content{padding:16px 12px 30px}.intro{display:block;margin-bottom:14px}.intro h2{font-size:24px}.intro p{font-size:11px;line-height:1.55}.live-status{display:none}.workflow{grid-template-columns:repeat(2,1fr);gap:12px;padding:14px;margin-bottom:18px}.flow-step{padding:0}.step-icon{width:31px;height:31px}.flow-step span{display:none}.metrics{grid-template-columns:repeat(2,1fr);margin-bottom:18px}.metric{padding:14px 12px;min-height:89px;border-right:1px solid var(--line)!important;border-bottom:1px solid var(--line)}.metric:nth-child(even){border-right:0!important}.metric:nth-last-child(-n+2){border-bottom:0}.metric-value{font-size:23px}.grid-top{gap:14px}.panel-head{padding:14px}.pipeline-body{padding:14px}.stage-list{grid-template-columns:repeat(3,1fr)}.stage:nth-child(n+4){display:none}.opportunity{padding:14px}.opp-actions{display:grid;grid-template-columns:1fr 1fr}.workspace-toolbar{display:none}.lead-table{display:none}.mobile-leads{display:grid}.lead-card{padding:14px;border-bottom:1px solid var(--line);display:grid;gap:11px}.lead-card:last-child{border-bottom:0}.lead-card-top{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.lead-card h4{font-size:13px;margin:0}.lead-card p{font-size:10px;color:var(--muted);margin:4px 0 0}.lead-card-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px}.lead-card-grid div{background:#f8fafc;border-radius:9px;padding:9px}.lead-card-grid span{display:block;font-size:9px;color:#98a2b3;margin-bottom:4px}.lead-card-grid strong{font-size:11px}.lead-card-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.lead-card-actions button,.lead-card-actions .action-link{min-height:44px;border-radius:9px;font-size:10px;font-weight:700}.lead-card-actions .open{background:#101828;color:#fff;border:0}.lead-card-actions .review{background:#fff;color:#344054;border:1px solid var(--line-strong)}.bottom-grid{gap:12px}.mobile-bottom-nav{position:fixed;display:flex;left:10px;right:10px;bottom:10px;background:#0d1626;border:1px solid rgba(255,255,255,.08);border-radius:15px;padding:6px;z-index:40;box-shadow:0 16px 40px rgba(2,6,23,.28)}.mobile-bottom-nav a{flex:1;height:48px;display:grid;place-items:center;color:#8090aa;font-size:9px;font-weight:700;gap:2px}.mobile-bottom-nav a.active{color:#fff;background:#18243a;border-radius:11px}.mobile-bottom-nav svg{width:18px;height:18px}}
@media(max-width:390px){.intro h2{font-size:21px}.top-actions .primary span{display:none}.workflow{grid-template-columns:repeat(2,1fr)}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
`;

export function renderDashboard(leads: Awaited<ReturnType<LeadStore["all"]>>): string {
  const report = buildReport(leads);
  const sorted = [...leads].sort((a, b) => (b.score?.total ?? -1) - (a.score?.total ?? -1));
  const topLead = sorted[0];

  const metrics = [
    ["Total leads", report.totalLeads, "Across active markets"],
    ["Qualified", report.qualifiedOrBeyond, "Qualified or beyond"],
    ["Demo ready", report.counts.demo_ready, "Awaiting review"],
    ["Approved", report.counts.approved, "Ready for contact"],
    ["Won", report.counts.won, "Closed customers"],
    ["Pipeline value", `$${report.projectedPipelineValue.toLocaleString()}`, "Projected value"]
  ].map(([label, value, hint]) => `<div class="metric"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-foot">${hint}</div></div>`).join("");

  const workflowData = [
    ["Find", report.totalLeads, "Discover businesses"],
    ["Audit", stageCount(report, "audited"), "Verify web presence"],
    ["Demo", stageCount(report, "demo_ready"), "Generate concept"],
    ["Approve", stageCount(report, "approved"), "Human review"],
    ["Contact", stageCount(report, "contacted") + stageCount(report, "responded"), "Zoho outreach"],
    ["Close", stageCount(report, "won") + stageCount(report, "lost"), "Win or learn"]
  ];
  const workflow = workflowData.map(([name, count, detail], index) => `<div class="flow-step ${index === 0 ? "is-live" : ""}"><div class="step-icon">${flowIcon(String(name))}</div><div><strong>${name}</strong><span>${count} · ${detail}</span></div></div>`).join("");

  const pipelineCounts = [
    ["New", stageCount(report, "new")],
    ["Audited", stageCount(report, "audited")],
    ["Qualified", stageCount(report, "qualified")],
    ["Demo ready", stageCount(report, "demo_ready")],
    ["Approved", stageCount(report, "approved")],
    ["Won", stageCount(report, "won")]
  ] as const;
  const denominator = Math.max(1, pipelineCounts.reduce((sum, [, count]) => sum + count, 0));
  const segments = pipelineCounts.map(([, count], index) => `<div class="seg s${index + 1}" style="width:${Math.max(4, Math.round((count / denominator) * 100))}%"></div>`).join("");
  const stages = pipelineCounts.map(([label, count]) => `<div class="stage"><em></em><strong>${count}</strong><span>${label}</span></div>`).join("");

  const topOpportunity = topLead ? `<div class="opportunity"><div class="opp-top"><div><h4>${escapeHtml(topLead.businessName)}</h4><div class="meta">${escapeHtml(topLead.category || "Lead")} · ${escapeHtml(topLead.market || "Market not set")}</div></div><div class="opp-score"><strong>${topLead.score?.total ?? "—"}</strong><span>score</span></div></div><div class="signal-list">${topSignals(topLead).map((signal) => `<div class="signal"><i></i>${escapeHtml(signal)}</div>`).join("")}</div><div class="opp-actions"><a class="secondary-btn action-link" href="#leads">Open lead</a>${topLead.stage === "qualified" ? `<button class="outline-btn" onclick="alert('Generate this lead from the CLI: npm run wga -- generate --lead ${escapeHtml(topLead.id)}')">Generate demo</button>` : actionMarkup(topLead) || `<a class="outline-btn action-link" href="#leads">Review evidence</a>`}</div></div>` : `<div class="empty-state"><strong>No production leads yet</strong><span>Scout a market to start the pipeline.</span></div>`;

  const rows = sorted.map((lead) => `<tr><td><div class="lead-name"><div class="avatar">${escapeHtml(initials(lead.businessName))}</div><div><strong>${escapeHtml(lead.businessName)}</strong><span>${escapeHtml(lead.category || "Uncategorized")}</span></div></div></td><td>${escapeHtml(lead.market || "—")}</td><td><span class="score-num">${lead.score?.total ?? "—"}</span></td><td><span class="stage-pill ${stageClass(lead.stage)}">${escapeHtml(stageLabel(lead.stage))}</span></td><td>${escapeHtml(primarySignal(lead))}</td><td>${websiteLink(lead)}</td><td><div class="table-actions">${actionMarkup(lead) || `<span class="muted">No action</span>`}</div></td></tr>`).join("");

  const mobileCards = sorted.map((lead) => `<article class="lead-card"><div class="lead-card-top"><div><h4>${escapeHtml(lead.businessName)}</h4><p>${escapeHtml(lead.category || "Lead")} · ${escapeHtml(lead.market || "Market not set")}</p></div><span class="stage-pill ${stageClass(lead.stage)}">${escapeHtml(stageLabel(lead.stage))}</span></div><div class="lead-card-grid"><div><span>Score</span><strong>${lead.score?.total ?? "—"}</strong></div><div><span>Signal</span><strong>${escapeHtml(primarySignal(lead))}</strong></div><div><span>Market</span><strong>${escapeHtml(lead.market || "—")}</strong></div></div><div class="lead-card-actions">${lead.website ? `<a class="open action-link" href="${escapeHtml(lead.website)}" target="_blank" rel="noreferrer">Open website</a>` : `<a class="open action-link" href="#leads">Open lead</a>`}${actionMarkup(lead) || `<button class="review" onclick="alert('No action is unlocked at this stage yet.')">Review lead</button>`}</div></article>`).join("");

  const agents = [
    ["Scout", "Searching local service businesses", "Running", "Find"],
    ["Auditor", "Evidence checks and opportunity scoring", "Idle", "Audit"],
    ["Designer", config.geminiApiKey ? "Gemini-backed demo concepts" : "Fallback demo concepts", config.geminiApiKey ? "Ready" : "Fallback", "Demo"],
    ["Sales", config.zohoMcpUrl ? "Approved outreach through Zoho" : "Zoho Mail not configured", config.zohoMcpUrl ? "Ready" : "Pending", "Contact"]
  ].map(([name, description, state, icon]) => `<div class="agent-row"><div class="agent-icon">${flowIcon(icon)}</div><div class="agent-copy"><strong>${name}</strong><span>${description}</span></div><span class="agent-state ${state === "Idle" || state === "Pending" ? "idle" : ""}">${state}</span></div>`).join("");

  const integrations = [
    ["Gemini AI", Boolean(config.geminiApiKey), config.geminiApiKey ? `${config.geminiModel} · search supplement` : "Not configured"],
    ["OpenStreetMap", true, `${config.overpassUrls.length} endpoint${config.overpassUrls.length === 1 ? "" : "s"} configured`],
    ["Zoho Mail", Boolean(config.zohoMcpUrl), config.zohoMcpUrl ? "Human-approved outreach only" : "Not configured"],
    ["Zoho Books", Boolean(config.zohoBooksMcpUrl), config.zohoBooksMcpUrl ? "Read-only accounting assistant" : "Not configured"]
  ].map(([name, healthy, detail]) => `<div class="health-row"><div><strong>${name}</strong><span>${detail}</span></div><span class="health-status ${healthy ? "" : "warn"}">${healthy ? "Connected" : "Pending"}</span></div>`).join("");

  const emptyLeads = `<div class="empty-state"><strong>No leads yet</strong><span>Use the scout command to find local website opportunities.</span></div>`;

  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light"><title>TechTactics Web Growth Command Center</title><style>${CSS}</style></head><body>
<div class="app"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">TT</div><div class="brand-copy"><strong>TechTactics</strong><span>Web Growth</span></div></div><nav class="nav" aria-label="Primary navigation"><div class="nav-label">Workspace</div><a class="active" href="#overview">Overview</a><a href="#pipeline">Pipeline<span class="nav-badge">${report.qualifiedOrBeyond}</span></a><a href="#leads">Leads<span class="nav-badge">${report.totalLeads}</span></a><a href="#agents">Agents</a><div class="nav-label">Operations</div><a href="#inbox">Inbox</a><a href="#accounting">Accounting</a><a href="#legal">Legal</a><a href="#integrations">Integrations</a></nav><div class="sidebar-footer"><div class="system-card"><span class="status-dot"></span><div><strong>Systems operational</strong><span>Human approval enabled</span></div></div></div></aside><div class="overlay" id="overlay" onclick="toggleMenu(false)"></div>
<main class="main"><header class="topbar"><div class="page-title"><button class="icon-btn mobile-menu" aria-label="Open navigation" onclick="toggleMenu(true)"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button><h1>Web Growth Command Center</h1></div><div class="top-actions"><button class="icon-btn" aria-label="Refresh dashboard" onclick="location.reload()"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M20 6v5h-5M4 18v-5h5"/><path d="M6.5 8A7 7 0 0 1 18 6l2 5M4 13l2 5a7 7 0 0 0 11.5-2"/></svg></button><button class="primary" onclick="showScoutHelp()"><span>＋</span><span>Scout leads</span></button></div></header>
<div class="content" id="overview"><section class="intro"><div><h2>Turn local businesses into qualified website opportunities.</h2><p>Scout, verify, audit, and move only evidence-backed prospects into your human-approved sales pipeline. Nothing is sent automatically.</p></div><div class="live-status"><i></i>Live workspace · VM 100</div></section><section class="workflow" aria-label="Operating workflow">${workflow}</section><section class="metrics" aria-label="Pipeline metrics">${metrics}</section>
<section class="grid-top" id="pipeline"><article class="panel"><div class="panel-head"><div><h3>Pipeline</h3><p>Current lead distribution by stage</p></div><a class="text-link" href="#leads">Open pipeline →</a></div><div class="pipeline-body"><div class="pipeline-rail" aria-hidden="true">${segments}</div><div class="stage-list">${stages}</div></div></article><article class="panel"><div class="panel-head"><div><h3>Top opportunity</h3><p>Highest evidence-backed score</p></div><a class="text-link" href="#leads">Review →</a></div>${topOpportunity}</article></section>
<section class="panel workspace" id="leads"><div class="panel-head"><div><h3>Lead workspace</h3><p>Evidence, stage, and next action in one place</p></div><div class="workspace-toolbar"><label class="search"><span>⌕</span><input aria-label="Search leads" placeholder="Search leads" oninput="filterLeads(this.value)"></label><button class="filter-btn" onclick="filterHighScore()">Score 35+</button></div></div>${leads.length ? `<table class="lead-table"><thead><tr><th>Business</th><th>Market</th><th>Score</th><th>Stage</th><th>Primary signal</th><th>Website</th><th>Actions</th></tr></thead><tbody id="leadRows">${rows}</tbody></table><div class="mobile-leads" id="mobileLeadCards">${mobileCards}</div>` : emptyLeads}</section>
<section class="bottom-grid"><article class="panel" id="agents"><div class="panel-head"><div><h3>Agent operations</h3><p>Specialists and current task state</p></div><a class="text-link" href="#integrations">Manage agents →</a></div><div class="ops-list">${agents}</div></article><article class="panel" id="integrations"><div class="panel-head"><div><h3>Integration health</h3><p>Runtime connections and safeguards</p></div><a class="text-link" href="#integrations">Settings →</a></div><div class="health">${integrations}</div></article></section>
<section class="bottom-grid"><article class="panel" id="inbox"><div class="panel-head"><div><h3>Inbox</h3><p>Prospect replies and follow-up review</p></div></div><div class="health"><div class="health-row"><div><strong>Zoho Mail</strong><span>${config.zohoMcpUrl ? "Connection ready for reviewed reads and replies." : "Connect Zoho Mail to surface conversations here."}</span></div><span class="health-status ${config.zohoMcpUrl ? "" : "warn"}">${config.zohoMcpUrl ? "Ready" : "Pending"}</span></div></div></article><article class="panel" id="accounting"><div class="panel-head"><div><h3>Accounting</h3><p>Read-only Zoho Books support</p></div></div><div class="health"><div class="health-row"><div><strong>Zoho Books</strong><span>${config.zohoBooksMcpUrl ? "Accounting assistant connection is configured." : "Read-only accounting connection is not configured yet."}</span></div><span class="health-status ${config.zohoBooksMcpUrl ? "" : "warn"}">${config.zohoBooksMcpUrl ? "Read only" : "Pending"}</span></div></div></article></section><section class="panel legal-panel" id="legal"><div class="panel-head"><div><h3>Legal</h3><p>Drafting support and owner review</p></div></div><div class="health"><div class="health-row"><div><strong>Human review required</strong><span>Binding decisions remain with TechTactics ownership and qualified professionals.</span></div><span class="health-status">Guardrail</span></div></div></section></div></main></div>
<nav class="mobile-bottom-nav" aria-label="Mobile navigation"><a class="active" href="#overview">Overview</a><a href="#leads">Leads</a><a href="#pipeline">Pipeline</a><a href="#agents">Agents</a></nav>
<script>
function toggleMenu(open){const s=document.getElementById('sidebar'),o=document.getElementById('overlay');s?.classList.toggle('open',open);o?.classList.toggle('show',open)}
function showScoutHelp(){alert('Scout from VM 100 with: docker exec -it web-growth-agent node dist/src/cli.js scout --market "Prairieville, LA" --category plumber --max-results 10 --source auto')}
function filterLeads(value){const q=value.toLowerCase();document.querySelectorAll('#leadRows tr,.mobile-leads .lead-card').forEach((el)=>{el.style.display=el.textContent?.toLowerCase().includes(q)?'':'none'})}
function filterHighScore(){document.querySelectorAll('#leadRows tr').forEach((row)=>{const score=Number(row.querySelector('.score-num')?.textContent||0);row.style.display=score>=35?'':'none'});document.querySelectorAll('.mobile-leads .lead-card').forEach((card)=>{const score=Number(card.querySelector('.lead-card-grid strong')?.textContent||0);card.style.display=score>=35?'':'none'})}
async function approve(id){const r=await fetch('/api/leads/'+encodeURIComponent(id)+'/approve',{method:'POST'});if(!r.ok)alert(await r.text());else location.reload()}
async function sendZoho(id){if(!confirm('Send the approved outreach email through Zoho now?'))return;const r=await fetch('/api/leads/'+encodeURIComponent(id)+'/send',{method:'POST'});if(!r.ok)alert(await r.text());else location.reload()}
async function stage(id,next){const r=await fetch('/api/leads/'+encodeURIComponent(id)+'/stage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stage:next})});if(!r.ok)alert(await r.text());else location.reload()}
window.addEventListener('keydown',e=>{if(e.key==='Escape')toggleMenu(false)})
</script></body></html>`;
}
